name: ds_utils
description: A set of useful functions and libraries used in almost all Zette flutter apps.
version: 1.0.0
homepage: https://zette.dev
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+1
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  riverpod: ^2.5.1
  rxdart: ^0.27.7
  sentry_dio: ^7.19.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
