name: zette_utils
description: A set of useful functions and libraries used in almost all Zette flutter apps.
version: 1.0.0
homepage: https://zette.dev
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+1
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  riverpod: ^2.5.1
  rxdart: ^0.28.0
  sentry_dio: ^8.5.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
