name: zette_utils
description: A set of useful functions and libraries used in almost all Zette flutter apps.
version: 1.0.0
homepage: https://zette.dev
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+2
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  logger: ^2.4.0
  ms_map_utils: ^1.1.0
  riverpod: ^2.6.1
  rxdart: ^0.28.0
  sentry: ^8.9.0
  sentry_dio: ^8.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
