// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'enums.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

const _$USStateEnumMap = {
  USState.AL: 'AL',
  USState.AK: 'AK',
  USState.AZ: 'AZ',
  USState.AR: 'AR',
  USState.CA: 'CA',
  USState.CO: 'CO',
  USState.CT: 'CT',
  USState.DE: 'DE',
  USState.FL: 'FL',
  USState.GA: 'GA',
  USState.HI: 'HI',
  USState.ID: 'ID',
  USState.IL: 'IL',
  USState.IN: 'IN',
  USState.IA: 'IA',
  USState.KS: 'KS',
  USState.KY: 'KY',
  USState.LA: 'LA',
  USState.ME: 'ME',
  USState.MD: 'MD',
  USState.MA: 'MA',
  USState.MI: 'MI',
  USState.MN: 'MN',
  USState.MS: 'MS',
  USState.MO: 'MO',
  USState.MT: 'MT',
  USState.NE: 'NE',
  USState.NV: 'NV',
  USState.NH: 'NH',
  USState.NJ: 'NJ',
  USState.NM: 'NM',
  USState.NY: 'NY',
  USState.NC: 'NC',
  USState.ND: 'ND',
  USState.OH: 'OH',
  USState.OK: 'OK',
  USState.OR: 'OR',
  USState.PA: 'PA',
  USState.RI: 'RI',
  USState.SC: 'SC',
  USState.SD: 'SD',
  USState.TN: 'TN',
  USState.TX: 'TX',
  USState.UT: 'UT',
  USState.VT: 'VT',
  USState.VA: 'VA',
  USState.WA: 'WA',
  USState.WV: 'WV',
  USState.WI: 'WI',
  USState.WY: 'WY',
};
